import java.util.Scanner;
import java.util.InputMismatchException;
// This program works as the main method for the Pakuri Program. This program creates a Pakudex Object to manipulate and store Pakuri objects
public class PakuriProgram {
    public static void main(String[] args) {
        // Scanner declared to keep track of user inputs
        Scanner Scanner = new Scanner(System.in);
        // Pakudex Capacity and UserChoice must be initialized prior to the following code to avoid errors, so both initialized to 0
        int PakudexCapacity = 0;
        int UserChoice = 0;
        // Prints out the welcome message for the program
        System.out.println("Welcome to Pakudex: Tracker Extraordinaire!");
        // Boolean values below used in try/catch statements below
        boolean Success = false;
        boolean MenuSuccess = false;
        // try/catch statement to ensure array initialization is correct
        while (Success == false) {
            try {
                System.out.print("Enter max capacity of the Pakudex: ");
                PakudexCapacity = Scanner.nextInt();
                // Test array initialized to ensure that negative values do not go through
                Pakudex pakudexTest = new Pakudex(PakudexCapacity);
                Success = true;
                // Catches if the user inputs a non-integer value
            } catch (InputMismatchException e) {
                System.out.print("Please enter a valid size.\n");
                Scanner.next();
            }
            // Catches if the user inputs a negative value
            catch (NegativeArraySizeException f) {
                System.out.print("Please enter a valid size.\n");
            }
        }
// New pakudex object generated utilizing user input after try/catch statement finishes
        Pakudex pakudex = new Pakudex(PakudexCapacity);
        System.out.println("The Pakudex can hold " + PakudexCapacity + " species of Pakuri.");
        PrintMenu();
        // Try catch statement to ensure that userOption is read correctly
        while (!MenuSuccess) {
            try {
                UserChoice = Scanner.nextInt();
                MenuSuccess = true;
                // Exception to if a user enters a string instead of an integer value caught
            } catch (InputMismatchException e) {
                System.out.println("Unrecognized menu selection!");
                PrintMenu();
                Scanner.next();
            }
        }
        // Species name of the Pakuri object generated by User Input
        String species;
        // While loop to continue getting input from user
        while (UserChoice >= 9999999 || UserChoice <= 9999999) {
            // If the user selects 1 as the option, displays the Pakuri generated within the Pakudex object array
            while (UserChoice == 1) {
                // Generates a string array assigned to the returned string array from the getSpeciesArray conducted on the Pakudex object
                String[] arraySpecies = pakudex.getSpeciesArray();
                // If the arraySpecies is null (getSpeciesArray returns null), displays an error message as there are no Pakuri objects within the Pakudex
                if (arraySpecies == null) {
                    System.out.println("No Pakuri in Pakudex yet!");
                    PrintMenu();
                    // Try Catch statement for menu options, same as the try-catch statement above for menuOption on line 38
                    MenuSuccess = false;
                    while (!MenuSuccess) {
                        try {
                            UserChoice = Scanner.nextInt();
                            MenuSuccess = true;
                            // Exception to if a user enters a string instead of an integer value caught
                        } catch (InputMismatchException e) {
                            System.out.println("Unrecognized menu selection!");
                            PrintMenu();
                            Scanner.next();
                        }
                    }
                    // If the arraySpecies is not null (getSpeciesArray returns something), displays a list of Pakuri objects within the pakudex object
                } else {
                    System.out.println("Pakuri In Pakudex:");
                    // Goes through arraySpecies array values and lists the array
                    for (int i = 0; i <= arraySpecies.length - 1; i++) {
                        if (arraySpecies[i] != null) {
                            System.out.println(i+1 + ". " + arraySpecies[i]);
                        }
                        // If arraySpecies has a null value (the number of Pakuri is less than the capacity of the array), breaks out of the loop
                        if (arraySpecies[i] == null) {
                            break;
                        }
                    }
                    PrintMenu();
                    MenuSuccess = false;
                    // Try Catch statement for menu options, same as the try-catch statement above for menuOption on line 38
                    while (!MenuSuccess) {
                        try {
                            UserChoice = Scanner.nextInt();
                            MenuSuccess = true;
                            // Exception to if a user enters a string instead of an integer value caught
                        } catch (InputMismatchException e) {
                            System.out.println("Unrecognized menu selection!");
                            PrintMenu();
                            Scanner.next();
                        }
                    }
                }
            }
            // If the user selects option 2, prompts the user to enter the name of the Pakuri object they want to see the statistics of and displays that Pakuri's stats
            while (UserChoice == 2) {
                System.out.print("Enter the name of the species to display: ");
                species = Scanner.next();
                // Calls on the getStats() method envoked on the Pakudex object, assigns results to a new integer array
                int[] pakuriShowStats = pakudex.getStats(species);
                // If the array is not null (getStats generated a value), displays the values of that Pakuri's stats
                if (pakuriShowStats != null) {
                    System.out.println("Species: " + species);
                    // invokes the pakuriShowstats value within the array established through line 1092
                    System.out.println("Attack: " + pakuriShowStats[0]);
                    System.out.println("Defense: " + pakuriShowStats[1]);
                    System.out.println("Speed: " + pakuriShowStats[2]);
                    PrintMenu();
                    MenuSuccess = false;
                    // Try Catch statement for menu options, same as the try-catch statement above for menuOption on line 38
                    while (!MenuSuccess) {
                        try {
                            UserChoice = Scanner.nextInt();
                            MenuSuccess = true;
                            // Exception to if a user enters a string instead of an integer value caught
                        } catch (InputMismatchException e) {
                            System.out.println("Unrecognized menu selection!");
                            PrintMenu();
                            Scanner.next();
                        }
                    }
                    // If the array is null (getStats does not return a value), provides an error statement stating that the Pakuri requested does not exist
                } else {
                    System.out.println("Error: No such Pakuri!");
                    PrintMenu();
                    MenuSuccess = false;
                    // Try Catch statement for menu options, same as the try-catch statement above for menuOption on line 38
                    while (!MenuSuccess) {
                        try {
                            UserChoice = Scanner.nextInt();
                            MenuSuccess = true;
                            // Exception to if a user enters a string instead of an integer value caught
                        } catch (InputMismatchException e) {
                            System.out.println("Unrecognized menu selection!");
                            PrintMenu();
                            Scanner.next();
                        }
                    }
                }
            }
// If the user selects option 3, adds a Pakuri object to the Pakudex array of objects
            while (UserChoice == 3) {
                // Creates a boolean value to ensure that the addPakuri method returns correct values
                boolean pakuriAdded = false;
                // Double checks to make sure that the pakudex array object of pakuri is not full
                if (pakudex.getSize() != pakudex.getCapacity()) {
                    System.out.print("Enter the name of the species to add: ");
                    species = Scanner.next();
                    // Assigns a value to the pakuriAdded boolean variable to check if addPakuri was successful
                    pakuriAdded = pakudex.addPakuri(species);
                    // If PakuriAdded was successful, informs the user that the addition of that Pakuri was successful
                    if (pakuriAdded == true) {
                        System.out.println("Pakuri species " + species + " successfully added!");
                        PrintMenu();
                        MenuSuccess = false;
                        // Try Catch statement for menu options, same as the try-catch statement above for menuOption on line 38
                        while (!MenuSuccess) {
                            try {
                                UserChoice = Scanner.nextInt();
                                MenuSuccess = true;
                                // Exception to if a user enters a string instead of an integer value caught
                            } catch (InputMismatchException e) {
                                System.out.println("Unrecognized menu selection!");
                                PrintMenu();
                                Scanner.next();
                            }
                        }
                    }
                }
                // If the method is not invoked or if PakuriAdded was unsuccessful, provides the user with an error statement, telling the user that the pakuri array was full
                if (pakuriAdded == false) {
                    System.out.println("Error: Pakudex is full!");
                    PrintMenu();
                    MenuSuccess = false;
                    // Try Catch statement for menu options, same as the try-catch statement above for menuOption on line 38
                    while (!MenuSuccess) {
                        try {
                            UserChoice = Scanner.nextInt();
                            MenuSuccess = true;
                            // Exception to if a user enters a string instead of an integer value caught
                        } catch (InputMismatchException e) {
                            System.out.println("Unrecognized menu selection!");
                            PrintMenu();
                            Scanner.next();
                        }
                    }
                }
            }
            // If the user selects option 4, evolves the pakuri object which the user requests. Increases attack, speed, and defense stats of the pakuri requested
            while (UserChoice == 4) {
                // Prompts the user to provide input to which pakuri they would like to evolve
                System.out.print("Enter the name of the species to evolve: ");
                species = Scanner.next();
                // Boolean value pakuriEvolved used to check if pakuri object was successfully evolved
                boolean pakuriEvolved = pakudex.evolveSpecies(species);
                // If pakuriEvolved (evolvedSpecies method invoked on pakudex object) returns true, informs the user that the evolution was successful
                if (pakuriEvolved == true) {
                    System.out.println(species + " has evolved!");
                    PrintMenu();
                    MenuSuccess = false;
                    // Try Catch statement for menu options, same as the try-catch statement above for menuOption on line 38
                    while (!MenuSuccess) {
                        try {
                            UserChoice = Scanner.nextInt();
                            MenuSuccess = true;
                            // Exception to if a user enters a string instead of an integer value caught
                        } catch (InputMismatchException e) {
                            System.out.println("Unrecognized menu selection!");
                            PrintMenu();
                            Scanner.next();
                        }
                    }
                }
                // If pakuriEvolved (evolvedSpecies method invoked on pakudex object) returns false, informs the user that the evolution was unsuccessful
                if (pakuriEvolved == false) {
                    System.out.println("Error: No such Pakuri!");
                    PrintMenu();
                    MenuSuccess = false;
                    // Try Catch statement for menu options, same as the try-catch statement above for menuOption on line 38
                    while (!MenuSuccess) {
                        try {
                            UserChoice = Scanner.nextInt();
                            MenuSuccess = true;
                            // Exception to if a user enters a string instead of an integer value caught
                        } catch (InputMismatchException e) {
                            System.out.println("Unrecognized menu selection!");
                            PrintMenu();
                            Scanner.next();
                        }
                    }
                }

            }
            // If the user selects menu option 5, sorts the pakuri objects in the pakudex array based on their lexicographical order
            while (UserChoice == 5) {
                // invokes the sortPakuri method on the pakudex object
                pakudex.sortPakuri();
                System.out.println("Pakuri have been sorted!");
                PrintMenu();
                MenuSuccess = false;
                // Try Catch statement for menu options, same as the try-catch statement above for menuOption on line 38
                while (!MenuSuccess) {
                    try {
                        UserChoice = Scanner.nextInt();
                        MenuSuccess = true;
                        // Exception to if a user enters a string instead of an integer value caught
                    } catch (InputMismatchException e) {
                        System.out.println("Unrecognized menu selection!");
                        PrintMenu();
                        Scanner.next();
                    }
                }
            }
            // If the user selects menu option 6, provides the user with an exit message and exits the program
            while (UserChoice == 6) {
                System.out.println("Thanks for using Pakudex! Bye!");
                System.exit(0);
            }
            // If the user chooses an option that isn't supported by the program (options less than 1 and greater than 6), provides an error statement, prompts for additional user input
            if (UserChoice < 1 || UserChoice > 6) {
                System.out.println("Unrecognized menu selection!");
                PrintMenu();
                MenuSuccess = false;
                // Try Catch statement for menu options, same as the try-catch statement above for menuOption on line 38
                while (!MenuSuccess) {
                    try {
                        UserChoice = Scanner.nextInt();
                        MenuSuccess = true;
                        // Exception to if a user enters a string instead of an integer value caught
                    } catch (InputMismatchException e) {
                        System.out.println("Unrecognized menu selection!");
                        PrintMenu();
                        Scanner.next();
                    }
                }
            }
        }
    }
    // PrintMenu method prints the program's main menu along with its options, then prompts for user input
        public static void PrintMenu () {
            System.out.println("\nPakudex Main Menu");
            System.out.println("-----------------");
            System.out.println("1. List Pakuri");
            System.out.println("2. Show Pakuri");
            System.out.println("3. Add Pakuri");
            System.out.println("4. Evolve Pakuri");
            System.out.println("5. Sort Pakuri");
            System.out.println("6. Exit");
            System.out.print("\nWhat would you like to do? ");
        }
        }